library(aroma.affymetrix)
log <- verbose <- Arguments$getVerbose(-8, timestamp=TRUE)
options(digits=4)

cdf <- AffymetrixCdfFile$byChipType("GenomeWideSNP_6", tags="Full")
print(cdf)
gi <- getGenomeInformation(cdf)
print(gi)
si <- getSnpInformation(cdf)
print(si)
acs <- AromaCellSequenceFile$byChipType(getChipType(cdf, fullname=FALSE))
print(acs)

cdf <- AffymetrixCdfFile$byChipType("GenomeWideSNP_6", tags="Full")
csR <- AffymetrixCelSet$byName("HapMap270,6.0,CEU,testSet", cdf=cdf)
print(csR)
cs <- csR
par(mar=c(4,4,1,1)+0.1)
plotDensity(cs, lwd=2, ylim=c(0,0.40))
stext(side=3, pos=0, getFullName(cs))
# filename <- sprintf("%s,plotDensity.png", getFullName(cs))
# dev.print(png, file=filename, width=640, height=400)
acc <- AllelicCrosstalkCalibration(csR, model="CRMAv2")
print(acc)
csC <- process(acc, verbose=verbose)
print(csC)
cs <- csC
par(mar=c(4,4,1,1)+0.1)
plotDensity(cs, lwd=2, ylim=c(0,0.40))
stext(side=3, pos=0, getFullName(cs))
array <- 1
xlim <- c(-500,15000)
plotAllelePairs(acc, array=array, pairs=1:6, what="input", xlim=xlim/3)
filename <- sprintf("%s,plotAllelePairs.png", getFullName(csR))
dev.print(png, file=filename, width=800, height=580)
plotAllelePairs(acc, array=array, pairs=1:6, what="output", xlim=xlim)
filename <- sprintf("%s,plotAllelePairs.png", getFullName(csC))
dev.print(png, file=filename, width=800, height=580)
bpn <- BasePositionNormalization(csC, target="zero")
print(bpn)
csN <- process(bpn, verbose=verbose)
print(csN)
cs <- csN
par(mar=c(4,4,1,1)+0.1)
plotDensity(cs, lwd=2, ylim=c(0,0.40))
stext(side=3, pos=0, getFullName(cs))
# filename <- sprintf("%s,plotDensity.png", getFullName(cs))
# dev.print(png, file=filename, width=640, height=400)
array <- 1
xlim <- c(-500,15000)
acc2 <- AllelicCrosstalkCalibration(csN)
plotAllelePairs(acc2, array=array, pairs=1:6, what="input", xlim=1.5*xlim)
filename <- sprintf("%s,plotAllelePairs.png", getFullName(csN))
dev.print(png, file=filename, width=800, height=580)
